### PR TITLE
Feat/add jest

### LINKED ISSUE #1: Add tests
Is it worth at this point adding jest and adding a test for the utils/bem.ts file?

### PR DESCRIPTION
**Pull request by emma-r-slight**
Add Jest to template.  Add Typography component.

### CODE REVIEW

**Review by nobrayner — COMMENTED** [review]
It probably makes more sense to have the typography component in experience ui, and to use bulma styles...

**Comment by emma-r-slight** [comment]
Maybe? 🤷‍♀️  I've added after chatting with @marika-jane the other day.. She mentioned preferring a typography component similar to the Material UI one ... which this is.  Perhaps we could do both? Update the component In the experience UI to be something like this but with bulma styles?

**Comment by nobrayner** [comment]
Sorry, didn't realize there already was one. But yes - update the experience ui component to be more like this, just using bulma styles (if at all possible). That way the bulma overrides will actually work :stuck_out_tongue:

**Comment by emma-r-slight** [comment]
@nobrayner I have absolutely no idea of how to do that.... but i will investigate! 
I'll just make this PR add Jest.

**Review by marika-jane — APPROVED** [review]
Approved, I guess you will remove the typography component before merge

**Pull request merged**
